export { default as car } from './car.svg';
export { default as hero } from './hero.png';
export { default as logo } from './logo.svg';
export { default as magnifier } from './magnifier.svg';
export { default as house } from './House.svg';
export { default as facebook } from './facebook.svg';
export { default as instagram } from './instagram.svg';
export { default as linkedin } from './linkedin.svg';
export { default as youtube } from './youtube.svg';
export { default as call } from './call.svg';
export { default as bag } from './Bag.svg';
export { default as user } from './User Arrows.svg';
export { default as cube } from './Cube.svg';
export { default as object } from './Object Ungroup.svg';
export { default as scinery } from './Scenery.svg';
export { default as circle } from './Circle Layer.svg';
export { default as rocket } from './Rocket.svg';
export { default as one } from './one.png';
export { default as two } from './two.png';
export { default as three } from './three.png';
export { default as four } from './four.png';
export { default as plant } from './plant.jpeg';
export { default as arrow } from './right arrow.svg';
export { default as pig } from './pig.jpeg';
export { default as carOne } from './carOne.jpeg';
export { default as flying } from './flying.jpeg';
export { default as glass } from './glass.png';
export { default as decimal } from './decimal.jpg';
export { default as funny } from './funny.jpg';
export { default as maven } from './maven.jpg';
export { default as powell } from './powell.jpg';
export { default as c2s } from './c2montreal.png';
export { default as locomotive } from './locomotive.png';
export { default as silencio } from './silencio.png';
export { default as officestudio } from './officestudio.png';
export { default as forbes } from './forbes.svg';
export { default as macys } from './macys.svg';
export { default as mensHealth } from './menshealth.svg';
export { default as mrBeast } from './mrbeast.svg';